# Generated by Django 3.2.11 on 2022-03-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_newspagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateField(blank=True, verbose_name='Fecha Post'),
        ),
    ]
