# Generated by Django 3.2.11 on 2022-02-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_footeritems_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterItems',
        ),
    ]
