# Generated by Django 3.2.11 on 2022-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertext',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
