# Generated by Django 3.2.11 on 2022-02-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0013_filmpage_filmpagelistmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmpagelistmovies',
            name='page',
        ),
        migrations.DeleteModel(
            name='FilmPage',
        ),
        migrations.DeleteModel(
            name='FilmPageListMovies',
        ),
    ]
