# Generated by Django 3.2.11 on 2022-02-23 08:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_filmpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPage',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpage')),
                ('titulo', models.CharField(max_length=250, verbose_name='Introducción')),
                ('cuerpo', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpage',),
        ),
        migrations.CreateModel(
            name='TravelPage',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpage')),
                ('titulo', models.CharField(max_length=250, verbose_name='Introducción')),
                ('cuerpo', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpage',),
        ),
    ]
