# Generated by Django 3.2.11 on 2022-02-27 20:03

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220224_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpage',
            name='location',
            field=djgeojson.fields.PointField(default=0),
            preserve_default=False,
        ),
    ]
