# Generated by Django 3.2.11 on 2022-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_travelpage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpage',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
