# Generated by Django 3.2.11 on 2022-02-28 20:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_librodetailpage'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0021_alter_travelpage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpage')),
                ('titulo', models.CharField(max_length=250, verbose_name='Introducción')),
                ('cuerpo', wagtail.core.fields.RichTextField(blank=True)),
                ('libros', modelcluster.fields.ParentalManyToManyField(blank=True, to='libros.Libro')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpage',),
        ),
        migrations.DeleteModel(
            name='MusicPage',
        ),
    ]
