# Generated by Django 3.2.11 on 2022-02-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220228_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='titulo',
        ),
    ]
