# Generated by Django 3.2.11 on 2022-03-01 11:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0006_auto_20220209_1950'),
        ('blog', '0023_auto_20220228_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmpage',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='filmpage',
            name='pelis',
        ),
        migrations.RemoveField(
            model_name='filmpage',
            name='titulo',
        ),
        migrations.CreateModel(
            name='PeliculasOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_pelis', to='blog.filmpage')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pelis.pelicula')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
