# Generated by Django 3.2.11 on 2022-03-07 17:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_librodetailpage'),
        ('blog', '0028_remove_blogcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='libros',
        ),
        migrations.CreateModel(
            name='LibrosOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='libros.libro')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_libros', to='blog.bookpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
