# Generated by Django 3.2.11 on 2022-02-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Footer items',
            },
        ),
    ]
