# Generated by Django 3.2.11 on 2022-02-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footeritems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterItems',
        ),
    ]
